name: 'Inno Setup Action'
author: 'Minionguyjpro'
branding:
  icon: 'box'
  color: 'green'
description: 'GitHub action to compile .iss (Inno Setup Script) files.'

inputs:
  path:
    description: 'Path to input .iss script file'
    required: true
  options:
    description: 'Extra arguments/options to include. Include the slashes for them.'
    required: true
    
runs:
  using: 'node16'
  main: 'dist/index.js'
